baseURL = "https://dclcats.gitee.io/"
languageCode = "zh-cn"
title = "灿灿的博客网"
theme = "ananke"

defaultContentLanguage = "zh"

# fix 相对路径图片问题
uglyurls = true
# fix 图片路径大小写敏感问题
disablePathToLower = true

# emoji 支持开启
# enableEmoji = true

# 通过 gitinfo 更新文章内容日期信息
# enableGitInfo = true

# 分页
# paginate = 10

summaryLength = 3

[taxonomies]
  tag = "tags"
  series = "series"
  category = "categories"
