
# featured_image = "https://themes.gohugo.io/theme/gohugo-theme-ananke/images/gohugo-default-sample-hero-image.jpg"
featured_image = "/images/gohugo-default-sample-hero-image.jpg"
favicon = "/images/ico/favicon.jpg"
