baseURL = "https://dclcats.github.io/"
title = "灿灿的博客网 | staging"

# 构建配置 设置 草稿 / 过期 / 未来文章可使用
buildDrafts = true 
buildExpired = true
buildFuture = true



[params]

  [params.busuanzi]         # count web traffic by busuanzi                             # 是否使用不蒜子统计站点访问量
    enable = false
    siteUV = false
    sitePV = false
    pagePV = false