baseURL = "https://dclcats.gitee.io/"

[params]
  [params.reward]                                         # 文章打赏
    enable = true
    wechat = "/pay/wechat-reward-image.jpeg"           # 微信二维码
    alipay = "/pay/alipay-reward-image.jpeg"           # 支付宝二维码
